server:
  port: 8080


spring:
  profiles:
    active: dev
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
