# Tomcat
server:
  port: 8080

# Spring
spring:
  profiles:
    active: dev
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatisPlus
mybatis-plus:
  type-aliases-package: com.blog.pojo.po
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-field: is_delete
  configuration:
    map-underscore-to-camel-case: true